apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ohmesh-data
  labels:
    app.kubernetes.io/name: ohmesh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
