apiVersion: v1
kind: Secret
metadata:
  name: ohmesh-oauth
  namespace: ohmesh
type: Opaque
stringData:
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
